using Figgle;
using System;

namespace Mastermind_App
{
    class Program
    {
        static void Main(string[] args)
        {
            //created a new mastermind to allow me to use the methods made in this class
            Mastermind mastermind = new Mastermind();

            //introduction to the game
            Console.ForegroundColor = ConsoleColor.DarkCyan;
            Console.WriteLine(FiggleFonts.Ogre.Render($"Mastermind"));
            Console.ForegroundColor = ConsoleColor.White;
            Console.WriteLine();
            Console.WriteLine($"Welcome to Mastermind!\n\nYou have 10 attempts to guess the 4 digits randomly generated by the computer." +
                $"\nEach number is in the range of 1-6. You will get (+) for correct numbers and " +
                $"\nlocations, (-) for numbers that are correct but it the wrong location, " +
                $"\nbut it the wrong location, and (_) for numbers that are neither.");

        Start: //used this to send the user back to top (out of loop) to restart the game
            //getting the computer array through a method (outside of loop so this doesn't change each attempt 
            int[] computerGuessArray = mastermind.computerArray();
            //setting amount of attempts for the loop
            int remainingAttempts = 10;
            //setting up a string to use to compare against the string generated in the compare arrays method
            string rightAnswer = "++++";

            //set a while loop to keep looping while there are remaining attempts (had a for loop before but changed it)
            while (remainingAttempts >= 0)
            {
                //different prompts for attempts
                if (remainingAttempts == 10)
                {
                    Console.WriteLine();
                    Console.Write($"Please enter 4 numbers (seperated by space) to get started:");
                }
                else
                {
                    Console.WriteLine();
                    Console.Write($"Enter your next guess:");
                }

                //gather the users guess each attempt
                string userGuess = Console.ReadLine();

                //send the user's guess string to get their array of ints
                int[] userGuessArray = mastermind.userGuessArray(userGuess);

                //send the user's guess array and computer array to a method that compares them and results in a string 
                string response = mastermind.CompareArrays(userGuessArray, computerGuessArray);

                //checking to see if the user's results contain the right answer
                if (response.Contains(rightAnswer))
                {
                    //this is the correct answer response and asks if player wants to play again
                    Console.WriteLine();
                    Console.ForegroundColor = ConsoleColor.Green;
                    Console.WriteLine("***Correct!***");
                    Console.ForegroundColor = ConsoleColor.White;
                    Console.WriteLine($"Computer Numbers were ({computerGuessArray[0]}, {computerGuessArray[1]}, {computerGuessArray[2]}, {computerGuessArray[3]}) results: ({response})");
                    Console.WriteLine();
                    Console.ForegroundColor = ConsoleColor.Yellow;
                    Console.Write("Play again? (Y/N)");
                    Console.ForegroundColor = ConsoleColor.White;

                    string playAgainW = Console.ReadLine();
                    if (playAgainW.ToUpper().Contains('Y'))
                    {
                        goto Start;
                    }
                    else
                    {
                        Console.ForegroundColor = ConsoleColor.DarkCyan;
                        Console.WriteLine("Thanks for playing! Goodbye!");
                        Console.ForegroundColor = ConsoleColor.White;
                        break;

                    }

                }
                else if (!response.Contains(rightAnswer) && remainingAttempts == 1)
                {
                    Console.WriteLine();
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine("***Incorrect*** ");
                    Console.ForegroundColor = ConsoleColor.White;
                    Console.Write("Sorry, out of attempts!");
                    Console.WriteLine();
                    Console.ForegroundColor = ConsoleColor.Yellow;
                    Console.Write("Play again? (Y/N)");
                    Console.ForegroundColor = ConsoleColor.White;
                    string playAgainL = Console.ReadLine();
                    if (playAgainL.ToUpper().Contains('Y'))
                    {
                        goto Start;
                    }
                    else
                    {
                        Console.ForegroundColor = ConsoleColor.DarkCyan;
                        Console.WriteLine("Thanks for playing! Goodbye!");
                        Console.ForegroundColor = ConsoleColor.White;
                        break;

                    }

                }
                else if (!response.Contains(rightAnswer) && remainingAttempts > 1)
                {
                    remainingAttempts--;
                    Console.WriteLine();
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine("***Incorrect*** ");
                    Console.ForegroundColor = ConsoleColor.White;
                    Console.WriteLine($"Your results: ({response}) Remaining Attempts: {remainingAttempts}");

                }

            }
        }
    }
}
